const APIURLS = {
    addDevice: '/addDevice',
    addDriver: '/addDriver',
    addFence: '/addGeoFence',
    addPoi: '/addPoi',
    addVehicle: '/addVehicle',
    addZone: '/addZone',
    assignZoneToPoi: '/assignZoneToPoi',
    createSession: 'createSession',
    deleteDevice: '/deleteDevice',
    deleteFence: '/deleteGeoFence',
    deletePoi: '/deletePoi',
    deleteVehicles: '/deleteVehicle',
    deleteZone: '/deleteZone',
    editDevice: '/editDevice',
    getAllDevices: '/getAllDevices',
    getAlldrivers: '/getAlldrivers',
    getAllGeoFence: '/getAllGeoFence',
    getAllPois: '/getAllPois',
    getAllVehicle: '/getVehicles',
    getAllZones: '/getAllZones',
    getUser: '/getUser',
    getVehicle: '/getVehicles',
    login: '/login',
    register: '/register',
    resendOtp: 'resendOtp',
    unAssignZoneToPoid: '/unAssignZoneToPoid',
    updateAvatar: 'updateAvatar',
    updateGeoFence: '/updateGeoFence',
    updatePoi: '/updatePoi',
    updateVehicle: '/updateVehicle',
    updateZone: '/updateZone',
    validateOtp: 'validateOtp',
};

export default APIURLS;
