const SCREENS = {
    ALERT: '/alert',
    ADDDEVICE: '/add-device',
    ADDDRIVER: '/add-driver',
    ADDGENSET: '/add-genset',
    ADDPOI: '/add-poi',
    ADDVEHICLE: '/add-vehicle',
    ADDZONE: '/add-zone',
    CONTACTUS: '/contact-us',
    DASHBOARD: '/dashboard',
    DEVICE: '/device',
    DRIVER: '/driver',
    DRIVERDETAIL: '/driver-detail',
    DEVICEDETAIL: '/device-detail',
    EXPIREDDEVICES: '/expired-devices',
    FENCE: '/fence',
    FORGOTPASSWORD: '/forgot-password',
    GENSET: '/genset',
    GENSETDETAIL: '/genset-detail',
    HISTORY: '/history',
    HOME: '/',
    LOGIN: '/login',
    LOCATE: '/locate',
    NOTFOUND: '/404',
    REFUNDDELIVERY: '/refund-delivery',
    RESETPASSWORD: '/reset-password',
    SELECTDATE: '/select-date',
    SETTINGS: '/settings',
    POI: '/poi',
    POIDETAIL: '/poi-detail',
    VEHICLE: '/vehicle',
    VEHICLEDETAIL: '/vehicle-detail',
    ZONE: '/zone',
    ZONEDETAIL: '/zone-detail',
};

export default SCREENS;
