const SCREENS = {
  LOGIN: '/login',
  FORGOTPASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  NOTFOUND: '/404',

  HOME: '/',
  DASHBOARD: '/dashboard',
  LOCATE: '/locate',
  FENCE: '/fence',
  SETTINGS: '/settings',
  ALERT: '/alert',
  HISTORY: '/history',
  CONTACTUS: '/contact-us',
  REFUNDDELIVERY: '/refund-delivery',
  EXPIREDDEVICES: '/expired-devices',
  SELECTDATE: '/select-date',
  GENSET: '/genset',
  ADDGENSET: '/add-genset',
  GENSETDETAIL: '/genset-detail',
  DRIVER: '/driver',
  ADDDRIVER: '/add-driver',
  DRIVERDETAIL: '/driver-detail',
  POI: '/poi',
  ZONE: '/zone',
  ADDZONE: '/add-zone',
  ZONEDETAIL: '/zone-detail',
};

export default SCREENS;
