// auth
export const SET_USER = 'SET_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const HANDLE_OTP = 'HANDLE_OTP';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_LOADING = 'CHANGE_LOADING';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const SET_SESSION_USER = 'SET_SESSION_USER';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const LOGIN_PHONE_USER = 'LOGIN_PHONE_USER';

// theme
export const DARK_THEME = "DARK_THEME";
export const LIGHT_THEME = "LIGHT_THEME";

// driver
export const GET_ALL_DRIVER = 'GET_ALL_DRIVER';
export const GET_ALL_DRIVER_ERROR = 'GET_ALL_DRIVER_ERROR';
export const GET_ALL_DRIVER_SUCCESS = 'GET_ALL_DRIVER_SUCCESS';
export const ADD_DRIVER = 'ADD_DRIVER';
export const ADD_DRIVER_ERROR = 'ADD_DRIVER_ERROR';
export const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';

// socket,
export const SET_DEVICES = 'SET_DEVICES';
export const SET_GPS_DATA = 'SET_GPS_DATA';
export const SET_VOLTAGE_BATTERY = 'SET_VOLTAGE_BATTERY';
export const SET_ALARMS = 'SET_ALARMS';
export const SET_DEVICE_SETTING = 'SET_DEVICE_SETTING';
export const SET_DEVICE_STATUS = 'SET_DEVICE_STATUS';
export const SET_ENGINE_STATUS = 'SET_ENGINE_STATUS';
export const SET_DEVICE_SIGNAL= 'SET_DEVICE_SIGNAL';
export const SET_GOT_SIGNAL = 'SET_GOT_SIGNAL';
export const SET_GPS_SIGNALS = 'SET_GPS_SIGNALS';



// export const SET_LOCK_STATUS = 'SET_LOCK_STATUS';

